### ISSUE TITLE
Extruder position shifted after activation

### ISSUE THREAD

**Issue by mindfest** [Xennis/OctoPrint-RestoreLevelingAfterG28#12]
Probles was as following

- Plugin installed
- Octopi restarted
- When printing, Z Axis was off about 20mm +, Bed / Y-Axis didn´t move (priming at the first corner)

Octopi 1.4.0 / Raspberry Pi 3b
After deactivation the extruder coordinates went back to normal

regards

mindfest

**Comment by Xennis** [comment]
Hey @mindfest, thanks for reporting. Please provide some additional information

1. What kind of Marlin leveling do you use (manual level, ...)?
2. When you are printing how do you manually activate your bed leveling? 
3. What's the output of `M420 V`?

Regards
Xennis

**Comment by Xennis** [comment]
No response for several days. Close it.
